esphome:
  name: esphome-web-fa61eb
  friendly_name: GroWatt

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "9e/FvM3vDD57hndlDHCg15b8gYzcYJhJP/gt1OG60bo="

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Fa61Eb"
    password: "zTxNU9psp9Tc"

captive_portal:

uart:
  id: mod_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600

modbus:
  id: modbus1
  flow_control_pin: D1

modbus_controller:
  - id: growatt
    address: 5
    modbus_id: modbus1
    setup_priority: -10

select:
  - platform: modbus_controller
    name: "Remote on/off switch"
    address: 00
    value_type: U_WORD
    optimistic: true
    optionsmap:
      "Off": 0
      "On": 1

switch:
  - platform: modbus_controller
    id: "spi_enabled"
    register_type: holding
    address: 01
    name: "SPI Enabled"
    bitmask: 00000001

  - platform: modbus_controller
    id: "auto_test_start"
    register_type: holding
    address: 01
    name: "Auto test start"
    bitmask: 00000010

  - platform: modbus_controller
    id: "lvfrt_enabled"
    register_type: holding
    address: 01
    name: "LVFRT enabled"
    bitmask: 00000100

  - platform: modbus_controller
    id: "freq_derating_enabled"
    register_type: holding
    address: 01
    name: "Frequency derating enabled"
    bitmask: 00000100

  - platform: modbus_controller
    id: "softstart_enabled"
    register_type: holding
    address: 01
    name: "Softstart enabled"
    bitmask: 00001000

  - platform: modbus_controller
    id: "drms_enabled"
    register_type: holding
    address: 01
    name: "DRMS enabled"
    bitmask: 00010000

  - platform: modbus_controller
    id: "powervoltfunc_enabled"
    register_type: holding
    address: 01
    name: "Power volt function enabled"
    bitmask: 00100000

number:
  - platform: modbus_controller
    modbus_controller_id: growatt
    id: active_p_rate
    name: "Active output percentage"
    address: 03
    value_type: U_WORD
    min_value: 0
    max_value: 100

  - platform: modbus_controller
    modbus_controller_id: growatt
    id: reactive_p_rate
    name: "Reactive output percentage"
    address: 04
    value_type: U_WORD
    min_value: 0
    max_value: 100

sensor:
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "Normal power (high)"
    id: normal_power_high
    register_type: holding
    address: 06
    unit_of_measurement: "VA"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "Normal power (low)"
    id: normal_power_low
    register_type: holding
    address: 07
    unit_of_measurement: "VA"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "Normal work PV voltage"
    id: normal_work_voltage
    register_type: holding
    address: 08
    unit_of_measurement: "V"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  ### PV1
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV1 voltage"
    id: pv1_voltage
    register_type: read
    offset: 0x1000
    address: 03
    unit_of_measurement: "V"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV1 input current"
    id: pv1_input_current
    register_type: read
    offset: 0x1000
    address: 04
    unit_of_measurement: "A"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV1 input power (high)"
    id: pv1_input_power_high
    register_type: read
    offset: 0x1000
    address: 05
    unit_of_measurement: "W"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV1 input power (low)"
    id: pv1_input_power_low
    register_type: read
    offset: 0x1000
    address: 06
    unit_of_measurement: "W"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
#
#  ### PV2
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV2 voltage"
#    id: pv2_voltage
#    register_type: read
#    address: 07
#    unit_of_measurement: "V"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV2 input current"
#    id: pv2_input_current
#    register_type: read
#    address: 08
#    unit_of_measurement: "A"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV2 input power (high)"
#    id: pv2_input_power_high
#    register_type: read
#    address: 09
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV2 input power (low)"
#    id: pv2_input_power_low
#    register_type: read
#    address: 10
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  ### PV3
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV3 voltage"
#    id: pv3_voltage
#    register_type: read
#    address: 11
#    unit_of_measurement: "V"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV3 input current"
#    id: pv3_input_current
#    register_type: read
#    address: 12
#    unit_of_measurement: "A"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV3 input power (high)"
#    id: pv3_input_power_high
#    register_type: read
#    address: 13
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV3 input power (low)"
#    id: pv3_input_power_low
#    register_type: read
#    address: 14
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  ### PV4
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV4 voltage"
#    id: pv4_voltage
#    register_type: read
#    address: 15
#    unit_of_measurement: "V"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV4 input current"
#    id: pv4_input_current
#    register_type: read
#    address: 16
#    unit_of_measurement: "A"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV4 input power (high)"
#    id: pv4_input_power_high
#    register_type: read
#    address: 17
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV4 input power (low)"
#    id: pv4_input_power_low
#    register_type: read
#    address: 18
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  ### PV5
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV5 voltage"
#    id: pv5_voltage
#    register_type: read
#    address: 19
#    unit_of_measurement: "V"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV5 input current"
#    id: pv5_input_current
#    register_type: read
#    address: 20
#    unit_of_measurement: "A"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV5 input power (high)"
#    id: pv5_input_power_high
#    register_type: read
#    address: 21
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV5 input power (low)"
#    id: pv5_input_power_low
#    register_type: read
#    address: 22
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  ### PV6
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV6 voltage"
#    id: pv6_voltage
#    register_type: read
#    address: 23
#    unit_of_measurement: "V"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV6 input current"
#    id: pv6_input_current
#    register_type: read
#    address: 24
#    unit_of_measurement: "A"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV6 input power (high)"
#    id: pv6_input_power_high
#    register_type: read
#    address: 25
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV6 input power (low)"
#    id: pv6_input_power_low
#    register_type: read
#    address: 26
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  ### PV7
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV7 voltage"
#    id: pv7_voltage
#    register_type: read
#    address: 27
#    unit_of_measurement: "V"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV7 input current"
#    id: pv7_input_current
#    register_type: read
#    address: 28
#    unit_of_measurement: "A"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV7 input power (high)"
#    id: pv7_input_power_high
#    register_type: read
#    address: 29
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV7 input power (low)"
#    id: pv7_input_power_low
#    register_type: read
#    address: 30
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  ### PV8
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV8 voltage"
#    id: pv8_voltage
#    register_type: read
#    address: 31
#    unit_of_measurement: "V"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV8 input current"
#    id: pv8_input_current
#    register_type: read
#    address: 32
#    unit_of_measurement: "A"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV8 input power (high)"
#    id: pv8_input_power_high
#    register_type: read
#    address: 33
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "PV8 input power (low)"
#    id: pv8_input_power_low
#    register_type: read
#    address: 34
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "Output power (high)"
#    id: output_power_high
#    register_type: read
#    address: 35
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "Output power (low)"
#    id: output_power_low
#    register_type: read
#    address: 36
#    unit_of_measurement: "W"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "Today generated energy (high)"
#    id: today_generated_energy_high
#    register_type: read
#    address: 53
#    unit_of_measurement: "kWH"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "Today generated energy (low)"
#    id: today_generated_energy_low
#    register_type: read
#    address: 54
#    unit_of_measurement: "kWH"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "Total generated energy (high)"
#    id: total_generated_energy_high
#    register_type: read
#    address: 55
#    unit_of_measurement: "kWH"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    name: "Total generated energy (low)"
#    id: total_generated_energy_low
#    register_type: read
#    address: 56
#    unit_of_measurement: "kWH"
#    value_type: U_WORD
#    accuracy_decimals: 1
#    filters:
#      - multiply: 0.1
#
#text_sensor:
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    id: growatt_inverter_firmware_high
#    register_type: holding
#    address: 09
#    raw_encode: NONE
#    name: "Firmware version (high)"
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    id: growatt_inverter_firmware_middle
#    register_type: holding
#    address: 10
#    raw_encode: NONE
#    name: "Firmware version (middle)"
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    id: growatt_inverter_firmware_low
#    register_type: holding
#    address: 11
#    raw_encode: NONE
#    name: "Firmware version (low)"
#
#  - platform: modbus_controller
#    modbus_controller_id: growatt
#    id: inverter_status
#    register_type: read
#    address: 1
#    raw_encode: NONE
#    name: "Inverter run state"
#    lambda: |-
#      uint16_t int_mode = (data[item->offset] << 8) + data[item->offset+1];
#      ESP_LOGD("main","Parsed operation mode int : %d", int_mode);
#      std::string mode_str;
#      switch (int_mode) {
#        case 0:  mode_str = "Waiting"; break;
#        case 1:  mode_str = "Normal"; break;
#        case 3:  mode_str = "Fault"; break;
#        default: mode_str = "Unknown"; break;
#
#      }
#      return mode_str;